### PR TITLE
Install sso

### PR DESCRIPTION
**Pull request by maleck13**
refactor to allow easier unit testing and more logical splits on code.

Takes the approach that each phase is a funciton that accepts the current state copies it modifies the copy and return the copy. 
All clients are interfaces allowing for unit testing

### CODE REVIEW

**Comment by maleck13** [comment]
This commit is the main one https://github.com/aerogear/keycloak-operator/pull/31/commits/0f238c5463472680747b0bc1e89cd1324e053026 as the others are removing vendor stuff

**Review by witmicko — COMMENTED** [review]
Looks good, two comments. Much tidier than it was before

**Comment by maleck13** [comment]
I want to remove ```sdk.``` but wanted to get this set of changes in as quite large and ppl coming back on monday

Will do more changes in another PR
My editor did the v12 etc

**Comment by maleck13** [comment]
I will merge and improve on it in next pr

**Pull request merged**
